apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-logger.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incident-logger.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: api-service
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    {{- include "incident-logger.selectorLabels" . | nindent 4 }}
    component: backend