apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-logger.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incident-logger.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    {{- include "incident-logger.selectorLabels" . | nindent 4 }}
    component: frontend