apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-logger.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incident-logger.labels" . | nindent 4 }}
    component: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - name: mysql-service
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  selector:
    {{- include "incident-logger.selectorLabels" . | nindent 4 }}
    component: mysql